clone:
  git:
    image: plugins/git
    depth: 1
    when:
      event: push

pipeline:
  lint-style:
    image: clojure:lein-2.8.3
    commands:
      - lein cljfmt check
    when:
      event: push
